/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bloomtech;

import java.io.InputStream;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

public class App {

    private static final float KNOT_TO_MPH_CONVERSION_FACTOR = 1.15f;

    public String getRawTextFromFile(String filename) {
        try {
            InputStream is = this.getClass().getClassLoader().getResourceAsStream(filename);
            String result = new BufferedReader(new InputStreamReader(is)).lines().collect(Collectors.joining("\n"));
            return result;
        } catch (Exception e) {
            throw new RuntimeException("Unable to read file", e);
        }
    }

    public List<String> splitLines(String rawHeadings) {
        String[] lines = rawHeadings.split("\n");
        return Arrays.asList(lines);
    }

    public List<String> filterHeadingsFromLines(List<String> lines) {
        String directionRegEx = "[ENSW]{1,2}";
        String timePatternRegEx = "\\d+\\.\\d+min";
        String speedRegEx = "\\d+\\.\\d+knots";

        Pattern directionPattern = Pattern.compile(directionRegEx);
        Pattern timePattern = Pattern.compile(timePatternRegEx);
        Pattern speedPattern = Pattern.compile(speedRegEx);

        List<String> output = new ArrayList<>();

        for (String line : lines) {
            Matcher directionMatcher = directionPattern.matcher(line);
            Matcher timeMatcher = timePattern.matcher(line);
            Matcher speedMatcher = speedPattern.matcher(line);

            if (directionMatcher.find() && timeMatcher.find() && speedMatcher.find()) {
                output.add(line);
            }
        }
        return output;
    }

    public Heading buildHeadingFromHeadingString(String headingString) {
        String headingRegEx = "([NESW]{1,2})\\s(\\d+\\.\\d+)min\\s(\\d+\\.\\d+)knots";
        Pattern headingPattern = Pattern.compile(headingRegEx);
        Matcher headingMatcher = headingPattern.matcher(headingString);
        if (headingMatcher.matches()) {
            String direction = headingMatcher.group(1);
            float time = Float.parseFloat(headingMatcher.group(2));
            float speed = Float.parseFloat(headingMatcher.group(3));
            return new Heading(direction, time, speed);
        } else {
            throw new RuntimeException("Unable to extract the required values from " + headingString);
        }
    }

    public List<Heading> getHeadingsFromHeadingStrings(List<String> headingStrings) {
        List<Heading> headingsList = new ArrayList<>();
        for (String headingString : headingStrings) {
            headingsList.add(this.buildHeadingFromHeadingString(headingString));
        }
        return headingsList;
    }

    public float computeTotalDistanceTraveledInMiles(List<Heading> headings) {
        float totalDistanceTraveled = 0.0f;
        for (Heading heading : headings) {
            totalDistanceTraveled += heading.getSpeedInKnots() * heading.getTime();
        }
        return totalDistanceTraveled * KNOT_TO_MPH_CONVERSION_FACTOR;
    }

    public static void main(String[] args) {
        App app = new App();
        // TODO: compose all functions as required to compute total distance traveled in miles
        String rawText = app.getRawTextFromFile("headings.txt");
        List<String> lines = app.splitLines(rawText);
        List<String> headingLines = app.filterHeadingsFromLines(lines);
        List<Heading> headings = app.getHeadingsFromHeadingStrings(headingLines);
        System.out.println("TOTAL DISTANCE TRAVELED IN MILES: " +
                app.computeTotalDistanceTraveledInMiles(headings));
    }
}
